### ISSUE TITLE
add an imports verification

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-docker#78]
/kind feature

**Describe the solution you'd like**
We verify golint and gofmt but we don't test goimports

**Comment by sethp-nr** [comment]
I'm just going to (helpfully?) leave this here:

```
run:
  deadline: 5m

linters-settings:
  gofmt:
    simplify: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  lll:
    line-length: 160
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - gochecknoinits
    - gochecknoglobals
    - dupl

golangci-lint-version: 1.17.x
```

and https://github.com/kubernetes-sigs/kubebuilder/issues/791
