### ISSUE TITLE
`capdctl version` command.

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-docker#88]
/kind feature

**Describe the solution you'd like**
When debugging, it's important to know exactly what environment you're running in. And unfortunately, there are a _lot_ of version variables when it comes to `cadp.` I think one single `capdctl version` command should return all the information about the environment, including:

* capdctl version
* docker runtime version
* kind version
* capd docker image
* capi docker image
* management cluster k8s control plane version
* management cluster k8s kubelet version
* constituent cluster k8s control plane version
* constituent cluster k8s kubelet version
* ... and probably more stuff I'm forgetting

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-docker version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chuckha** [comment]
This is a huge task, we should probably break it down into small pieces.

We don't need the kind version as we're only using the library, not the CLI. That dependency is managed in go.

I don't understand the use case for management & child cluster version listing, can you please expand on why those in particular would be useful?

- [ ] Enable `capdctl version` that prints the version of capdctl. We should [investigate ldflags](https://stackoverflow.com/questions/47509272/how-to-set-package-variable-using-ldflags-x-in-golang-build?rq=1)
- [ ] Scaffolding of the command, perhaps `capdctl environment-versions`?
- [ ] docker runtime version -- Shell out with `docker version`
- [ ] capd container image -- use client-go to get the capd deployment and extract the image
- [ ] capi container image -- use client-go to get the capi deployment and extract the image

**Comment by ashish-amarnath** [comment]
I agree. That was going to be my approach anyway. Going down the list 😄 
`ldflags` are how we can do this w/o using something like `bazel`

**Comment by ashish-amarnath** [comment]
PR1: Implementing version info for all capd binaries https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/89

**Comment by chuckha** [comment]
This is going to be super useful if we can port it to other providers or maybe make a generic thing that "finds versions of various things". 

maybe like

```
checks:
  - name: capi-image-version
     check_type:
        kind: k8s-deployment
        deployment_name: 'cluster-api'
  - name: capd-image-version
     check_type:
       kind: k8s-statefulset
       statefulset_name: 'capd'
  - name: docker

# And then run 
     
appenv --checks appenv-checks.yaml
capi-image: us.gcr.io/cluster-api/manager:v0.1.6:sha256abcd12345
capd-image: gcr.io/kubernetes-22222/manager:dev
docker-client: 18.09.2
docker-engine: 18.09.2
```
